### PR TITLE
Use new syntax when using Faraday to initialise connections

### PR DESCRIPTION
**Pull request by fsanggang**
### 📝 Description

We used to be able to initialise connections like

```
Faraday::Connection.basic_auth("key", "secret")
```

But this is now deprecated and warnings are thrown when running the `investapp` tests. Let's update with the [new syntax](https://lostisland.github.io/faraday/middleware/authentication) like

```
Faraday::Connection.request(:basic_auth, "key", "secret")
```

See the associated [story](https://vimaly.com/#j8mqm/t/X7c8KvgKbjMYihsHJ).

----

Related:
- https://github.com/sharesight/investapp/pull/9805
- https://github.com/sharesight/xero-ruby/pull/4 (this PR)

### CODE REVIEW

**Comment by fsanggang** [comment]
No CI? All specs 🟢 for me locally at least.

**Review by alto — APPROVED** [review]
💯

**Review by OBaddeley — APPROVED** [review]
👍🏼

**Comment by fsanggang** [comment]
Applying this update is a bit more complicated than I thought. I'm closing this because:

- [xero-ruby](https://github.com/sharesight/xero-ruby) is locked to a specific commit in investapp, because a previous attempt to keep our fork up to date with the official version was unsuccessful. This means that merging in this change won't have any effect.
- This deprecation has actually already been [updated](https://github.com/XeroAPI/xero-ruby/blob/master/lib/xero-ruby/api_client.rb#L301) in the official version. What we should do is use the official version and monkey-patch to add the functionality we need (sync using bank statements), and there is already a [Vimaly ticket](https://vimaly.com/#j8mqm/t/Keep_xero-ruby_gem_up-to-date_with_upstream_change.../xk7BskOTESNCIZB4U) for this. 

This doesn't block the changes in https://github.com/sharesight/investapp/pull/9805, so that will still be merged.

**Pull request closed without merging**
